# Generated by Django 3.0.3 on 2020-06-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200626_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Subcatergory',
            new_name='Subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
